name: Ada CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v3

    - name: Cache Alire toolchain
      uses: actions/cache@v4
      with:
        path: /home/runner/.config/alire
        key: ${{ runner.os }}-alire-${{ hashFiles('alire.toml') }}

    - name: Install Alire
      run: |
        curl -sSfL https://raw.githubusercontent.com/alire-project/alire/master/install.sh | sh -s -- -b ~/.local/bin
        echo "::add-path::${HOME}/.local/bin"

#    - name: Install dependencies
#      run: ~/.local/bin/alr get

    - name: Build project
      run: ~/.local/bin/alr build

    - name: Run program
      run: ./bin/hello
